---
driver:
  name: vagrant
  provider: <%= ENV['KITCHEN_PROVIDER'] || 'virtualbox' %>

driver_config:
    customize:
#      cpus: 2
#      memory: 2048	# 1.7
      memory: 4096	# 2.2.0

provisioner:
  name: ansible_playbook
  roles_path: ../../roles
  hosts: test-kitchen
  ansible_verbose: false
  ansible_verbosity: 2
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
#  name: chef_solo

platforms:
  - name: ubuntu-14.04
## currently not supporting centos
#  - name: centos-7.1

suites:
  - name: default
    run_list:
    attributes:

