---
- name: ES apt repo
  apt_repository:
    repo="deb http://packages.elasticsearch.org/elasticsearch/{{ elk_elasticsearch.version }}/{{ ansible_os_family|lower }} stable main"
    update_cache=yes
  when: ansible_os_family == 'Debian'
  become: yes

- name: Install ES apt packages
  apt: pkg=elasticsearch update_cache=yes state=latest
  become: yes
  when: ansible_os_family == 'Debian'
  notify: Restart elasticsearch

- name: bootstrap elasticsearch repository
  copy: src=elasticsearch.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: elasticsearch repo install
  yum: name=elasticsearch
       enablerepo=elasticsearch
       state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: elasticsearch repository enable
  ini_file: dest=/etc/yum.repos.d/elasticsearch.repo
            section=elasticsearch
            option=enabled
            value=1
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Curator PIP package
  pip: name=elasticsearch-curator state=latest
  become: yes

- name: ES config file
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root group=root mode=644
  become: yes
  notify: Restart elasticsearch

## https://github.com/elastic/elasticsearch/issues/9357
- name: Allow memlock in systemd config
  lineinfile:
    dest=/usr/lib/systemd/system/elasticsearch.service
    regexp='^LimitMEMLOCK='
    line='LimitMEMLOCK=infinity'
    insertafter='#LimitMEMLOCK=infinity'
    backup=yes

- name: Make monit to look after ES
  template:
    src=elasticsearch.monitrc.conf.j2
    dest=/etc/monit/conf.d/elasticsearch.monitrc.conf
    owner=root group=root mode=644
  become: yes
  notify: Restart monit
